### ISSUE TITLE
Glotz API Key as Environment Variable

### ISSUE THREAD

**Issue by slemens** [avpnusr/sickchill#1]
Hi,
I think it would be a good idea to set the Glotz Key through a environment variable within your start.sh script. If too many users use your dockerfile, your key will probably get blocked. 
I could try to write a small pull request if wanted.

Regards,
Sebastian

**Comment by avpnusr** [comment]
That's a really good idea :)
I would appreciate the pull request!

**Comment by avpnusr** [comment]
I implemented the "feature" in the startup-script and pushed the release just a minute ago.
Hopefully it works :)
