### ISSUE TITLE
PUID PGID as Environment Variables

### ISSUE THREAD

**Issue by zenprox** [avpnusr/sickchill#2]
Currently the permissions inside the container (i. e. sickchill-Folder) are set to root even when I start the container with -user=[UID:GID] parameter. Please support PUID and PGID as environment variables for setting the container permissions properly

**Comment by Technosoft2000** [comment]
Need this feature too for usage on a Synology NAS

**Comment by Technosoft2000** [comment]
I've created a modified image https://hub.docker.com/r/technosoft2000/sickchill and a pull request #3 for the changes.

**Comment by avpnusr** [comment]
Thanks a lot @Technosoft2000
